version: "3.8"
services:
  frontend:
    build: .
    container_name: web-front-app
    ports:
      - "${SERVICE_PORT}:${NGINX_PORT}"
    volumes:
      - ./:/app    # Optional: For development (live-reload)
      - /app/node_modules
    environment:
      NODE_ENV: "development"
      baseUrl: ${BASE_URL}
    restart: unless-stopped
