services:
  frontend:
    restart: unless-stopped
    image: ${IMAGE}:${TAG}
    container_name: web-front
    environment:
      baseUrl: ${BASE_URL}
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
